application: Private network
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#  a static file mapping
- url: /
  static_files: index.html
  upload: index.html

#css style file  
- url: /css.css
  static_files: css.css
  upload: css.css

#js file
- url: /js.js
  static_files: js.js
  upload: js.js
  
- url: .*
  script: main.app



