application: privsocial
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#  a static file mapping
- url: /
  static_files: login.html
  upload: login.html

#  a static file mapping
- url: /Error.html
  static_files: Error.html
  upload: Error.html
  
#  a static file mapping
- url: /index.html
  static_files: index.html
  upload: index.html 
  
#  a static file mapping
- url: /Arrangment.html
  static_files: Arrangment.html
  upload: Arrangment.html 
  
#  a static file mapping
- url: /Profile.html
  static_files: Profile.html
  upload: Profile.html 
  
# images
- url: /Images
  static_dir: Images
 
 #css style file  
- url: /login.css
  static_files: login.css
  upload: login.css

 #css style file  
- url: /login.css
  static_files: login.css
  upload: login.css
  
 #js style file  
- url: /javascript
  static_dir: javascript
  
 #js style file  
- url: /jQueryAssets
  static_dir: jQueryAssets
  
 #css style file  
- url: /Error.css
  static_files: Error.css
  upload: Error.css
  
 #css style file  
- url: /Profile.css
  static_files: Profile.css
  upload: Profile.css
  
#css style file  
- url: /Arrangement.css
  static_files: Arrangement.css
  upload: Arrangement.css
   
- url: .*
  script: main.app



